Add mir-core as a required dependency to the pkgconfig.
This will fix the following error when linking to this library:
`undefined reference to '_D3mir4conv12__ModuleInfoZ'`

Signed-off-by: Dan Printzell <xwildn00bx@gmail.com>